/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion2_proyectolab_fabio_katherine;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author KATHERINE
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_UsuarioCandidato = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_usuario_c2 = new javax.swing.JTextField();
        ag_usuario_candidato = new javax.swing.JButton();
        rb_femenino_c2 = new javax.swing.JRadioButton();
        rb_masculino_c2 = new javax.swing.JRadioButton();
        tf_nombre_c2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        tf_correo_c2 = new javax.swing.JTextField();
        jd_fecha_c2 = new com.toedter.calendar.JDateChooser();
        jd_UsuarioComun = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_usuario_c1 = new javax.swing.JTextField();
        tf_nombre_c1 = new javax.swing.JTextField();
        tf_correo_c1 = new javax.swing.JTextField();
        tf_direccion_c1 = new javax.swing.JTextField();
        tf_archivo_c1 = new javax.swing.JTextField();
        rb_femenino_c1 = new javax.swing.JRadioButton();
        rb_masculino_c1 = new javax.swing.JRadioButton();
        ag_usuario_comun = new javax.swing.JButton();
        jd_fecha_c1 = new com.toedter.calendar.JDateChooser();
        tf_contraseña_c1 = new javax.swing.JPasswordField();
        sexo2 = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Usuario Candidato");

        jLabel11.setText("Usuario");

        jLabel12.setText("Contraseña");

        jLabel13.setText("Nombre Completo");

        jLabel14.setText("Correo");

        jLabel15.setText("Sexo");

        jLabel16.setText("Fecha de nacimiento");

        tf_usuario_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuario_c2ActionPerformed(evt);
            }
        });

        ag_usuario_candidato.setText("Agregar");
        ag_usuario_candidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ag_usuario_candidatoActionPerformed(evt);
            }
        });

        rb_femenino_c2.setText("F");
        rb_femenino_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femenino_c2ActionPerformed(evt);
            }
        });

        rb_masculino_c2.setSelected(true);
        rb_masculino_c2.setText("M");

        tf_nombre_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombre_c2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        tf_correo_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_correo_c2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_UsuarioCandidatoLayout = new javax.swing.GroupLayout(jd_UsuarioCandidato.getContentPane());
        jd_UsuarioCandidato.getContentPane().setLayout(jd_UsuarioCandidatoLayout);
        jd_UsuarioCandidatoLayout.setHorizontalGroup(
            jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_nombre_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(tf_usuario_c2))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addComponent(rb_femenino_c2)
                        .addGap(18, 18, 18)
                        .addComponent(rb_masculino_c2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_correo_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jd_fecha_c2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(139, 139, 139))
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel10))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(ag_usuario_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_UsuarioCandidatoLayout.setVerticalGroup(
            jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tf_usuario_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(tf_nombre_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(tf_correo_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(rb_femenino_c2)
                            .addComponent(rb_masculino_c2)))
                    .addComponent(jd_fecha_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(ag_usuario_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Usuario Común ");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("fecha de nacimiento");

        jLabel5.setText("Correo");

        jLabel6.setText("sexo");

        jLabel7.setText("Nombre Completo");

        jLabel8.setText("Dirección");

        jLabel9.setText("Archivo de texto");

        tf_correo_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_correo_c1ActionPerformed(evt);
            }
        });

        tf_archivo_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_archivo_c1ActionPerformed(evt);
            }
        });

        rb_femenino_c1.setText("F");

        rb_masculino_c1.setSelected(true);
        rb_masculino_c1.setText("M");

        ag_usuario_comun.setText("Agregar");
        ag_usuario_comun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_comunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_UsuarioComunLayout = new javax.swing.GroupLayout(jd_UsuarioComun.getContentPane());
        jd_UsuarioComun.getContentPane().setLayout(jd_UsuarioComunLayout);
        jd_UsuarioComunLayout.setHorizontalGroup(
            jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_direccion_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(tf_nombre_c1)
                                    .addComponent(tf_usuario_c1)))
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(107, 107, 107)
                                .addComponent(rb_femenino_c1)
                                .addGap(18, 18, 18)
                                .addComponent(rb_masculino_c1)))
                        .addGap(82, 82, 82)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_archivo_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(jd_fecha_c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_correo_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(tf_contraseña_c1)))))
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(273, 273, 273)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ag_usuario_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );
        jd_UsuarioComunLayout.setVerticalGroup(
            jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tf_usuario_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_contraseña_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(tf_nombre_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_correo_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(rb_femenino_c1)
                            .addComponent(rb_masculino_c1)))
                    .addComponent(jd_fecha_c1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(tf_direccion_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_archivo_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(ag_usuario_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/programacion2_proyectolab_fabio_katherine/Sin título.png"))); // NOI18N

        jMenu1.setText("Sistema de Elecciones");

        jMenu3.setText("Registro");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Usuario Comun");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Usuario Candidato");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);

        jMenu4.setText("Login");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Usuario Común");

        jMenuItem3.setText("Perfil");
        jMenu5.add(jMenuItem3);

        jMenuItem6.setText("Ver Usuarios");
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Ver Candidatos");
        jMenu5.add(jMenuItem7);

        jMenuItem4.setText("Publicaciones Presidenciales");
        jMenu5.add(jMenuItem4);

        jMenuItem8.setText("Messenger");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem5.setText("Actas");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Usuario Candidato");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuario_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuario_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuario_c2ActionPerformed

    private void ag_usuario_candidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ag_usuario_candidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ag_usuario_candidatoActionPerformed

    private void rb_femenino_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femenino_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_femenino_c2ActionPerformed

    private void tf_nombre_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombre_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombre_c2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void tf_correo_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_correo_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_correo_c2ActionPerformed

    private void tf_correo_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_correo_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_correo_c1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jd_UsuarioCandidato.setModal(true);
        jd_UsuarioCandidato.pack();
        jd_UsuarioCandidato.setLocationRelativeTo(this);
        jd_UsuarioCandidato.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_UsuarioComun.setModal(true);
        jd_UsuarioComun.pack();
        jd_UsuarioComun.setLocationRelativeTo(this);
        jd_UsuarioComun.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void ag_usuario_comunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_comunMouseClicked
        // TODO add your handling code here:
        try {
             String usuario="",contraseña="",nombre="",correo="",sexo="",direccion="",text="";
        Date fecha_nacimiento;
        usuario=tf_usuario_c1.getText();
        contraseña=tf_contraseña_c1.getText();
        nombre=tf_nombre_c1.getText();
        correo=tf_correo_c1.getText();
        if(rb_masculino_c1.isSelected()){
            sexo="MASCULINO";
        }else{
            sexo="FEMENINO";
            
        }
        direccion=tf_direccion_c1.getText();
        fecha_nacimiento=jd_fecha_c1.getDate();
        text=tf_archivo_c1.getText();
        //String direccion, String Archivo, String nombre_usuario, String contraseña, Date fecha_nacimiento, String correo, String sexo, String nombre
        this.usuario.add(new Usuario_comun(direccion, text, usuario, contraseña, fecha_nacimiento, correo, sexo, nombre));
        JOptionPane.showMessageDialog(jd_UsuarioComun, "El usuario común se agregó con exito");
        
        tf_usuario_c1.setText("");
        tf_contraseña_c1.setText("");
        tf_nombre_c1.setText("");
        tf_correo_c1.setText("");
        tf_direccion_c1.setText("");
        tf_archivo_c1.setText("");
        rb_masculino_c1.setSelected(true);
        rb_femenino_c1.setSelected(false);
        
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioComun, "ocurrio un error y no se guardaron los datos");
        }
       
        
        
        
        
        
        
    }//GEN-LAST:event_ag_usuario_comunMouseClicked

    private void tf_archivo_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_archivo_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_archivo_c1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton ag_usuario_candidato;
    private javax.swing.JButton ag_usuario_comun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JDialog jd_UsuarioCandidato;
    private javax.swing.JDialog jd_UsuarioComun;
    private com.toedter.calendar.JDateChooser jd_fecha_c1;
    private com.toedter.calendar.JDateChooser jd_fecha_c2;
    private javax.swing.JRadioButton rb_femenino_c1;
    private javax.swing.JRadioButton rb_femenino_c2;
    private javax.swing.JRadioButton rb_masculino_c1;
    private javax.swing.JRadioButton rb_masculino_c2;
    private javax.swing.ButtonGroup sexo2;
    private javax.swing.JTextField tf_archivo_c1;
    private javax.swing.JPasswordField tf_contraseña_c1;
    private javax.swing.JTextField tf_correo_c1;
    private javax.swing.JTextField tf_correo_c2;
    private javax.swing.JTextField tf_direccion_c1;
    private javax.swing.JTextField tf_nombre_c1;
    private javax.swing.JTextField tf_nombre_c2;
    private javax.swing.JTextField tf_usuario_c1;
    private javax.swing.JTextField tf_usuario_c2;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuario=new ArrayList();

}
